name: build

on:
  push:
    branches:
      - main

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/medlemskap-sykepengerlytter:${{ github.sha }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: test and build
        run: ./gradlew test shadowJar
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: docker build -t $IMAGE .
      - name: Login to Github package registry
        run: docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push docker image
        run: docker push $IMAGE
      - name: Post failures to Slack
        if: failure()
        run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"$CHANNEL\", \"text\": \"$MESSAGE\", \"icon_emoji\": \":ghost:\"}" $WEBHOOK_URL
        env:
          MESSAGE: "Bygg feilet"
          CHANNEL: "#team-p3-medlemskap-notifications"
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
  deploypreprod:
    name: Deploy to Preprod
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-gcp
        RESOURCE: .nais/nais.yaml
        VAR: image=${{ env.IMAGE }}
  deployprod:
    name: Deploy to Prod
    needs: deploypreprod
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: prod-gcp
        RESOURCE: .nais/nais.yaml
        VAR: image=${{ env.IMAGE }}
